spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  application: 
    name: config-client1111
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
---

spring:
  profiles: test
  application: 
    name: config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
